photography_landing/photography_landing/urls.py
from django.contrib import admin
from django.urls import path,include
from webpage import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(),name='home'),
    path('webpage/', include("webpage.urls"))
]

photography_landing/webpage/urls.py
from django.urls import path
from . import views

app_name = 'web_application'
urlpatterns = [
    path('LA/',views.LaPage.as_view(),name='losangeles'),
    path('seattle/',views.SeattlePage.as_view(),name='seattle'),
    path('portland/',views.PortlandPage.as_view(),name='portland'),
    path('about/',views.AboutPage.as_view(),name='about'),
    path('contact/',views.ContactPage.as_view(),name='contact')
]

photography_landing/webpage/models.py
from django.db import models

# Create your models here.

photography_landing/webpage/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.

class HomePage(TemplateView):
    template_name = "webpage/home.html"

class LaPage(TemplateView):
    template_name = "webpage/losangeles.html"

class SeattlePage(TemplateView):
    template_name = "webpage/seattle.html"

class PortlandPage(TemplateView):
    template_name = "webpage/portland.html"

class AboutPage(TemplateView):
    template_name = "webpage/about.html"

class ContactPage(TemplateView):
    template_name = "webpage/contact.html"

photography_landing/webpage/templates/webpage/about.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block bodyblock %}
  <div class="jumbotron">
    <h1 class="display-2">About Me</h1>
    <br>
    <br>
    <div class="container">
      <p class="h1">Early Beginnings</p>
      <div class="row">
        <div id="fl-1" class="col">
          <p id="abtxt"class="text-justify">Ever since I was a boy I was obessed
          with cameras.
          My mother would let me snap pictures from cool cars to awesome houses.
          As I grew older with more practice, I began shooting shots of all the
          cities I traveled to.
          From <a class="text-danger"href="{% url 'web_application:losangeles' %}">
            Los Angeles</a>,
          to <a class="text-danger" href="{% url 'web_application:seattle' %}">Seattle</a>, and
          <a class="text-danger"href="{% url 'web_application:portland' %}">Portland</a>.
          Photograghy has been a passion since before I can remember, and I enjoy
          being able to snap life's
          precious moments. I pride myself on professionalism and courtesy! Feel
          free to shoot me an <a class="text-danger"href="{% url 'web_application:contact' %}">email</a> to discuss a photo shoot and
          pricing.</p>
        </div>
        <div id="f1-2"class="col">
          <img src="{% static 'images/camera.jpeg' %}" class="img-fluid" alt="Responsive image">
        </div>
      </div>
    </div>
  </div>


{% endblock %}

photography_landing/webpage/templates/webpage/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Lutton Photograghy</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static '/css/master.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Srisakdi" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Special+Elite|Srisakdi" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/brands.css" integrity="sha384-BKw0P+CQz9xmby+uplDwp82Py8x1xtYPK3ORn/ZSoe6Dk3ETP59WCDnX+fI1XCKK" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/fontawesome.css" integrity="sha384-4aon80D8rXCGx9ayDt85LbyUHeMWd3UiBaWliBlJ53yzm9hqN21A+o1pqoyK04h+" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark">
      <a class="navbar-brand" href="{% url 'home' %}">Lutton Photograghy</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'web_application:about' %}">About </a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Cities
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'web_application:losangeles' %}">Los Angeles</a>
              <a class="dropdown-item" href="{% url 'web_application:seattle' %}">Seattle</a>
              <a class="dropdown-item" href="{% url 'web_application:portland' %}">Portland</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'web_application:contact' %}">Contact Me</a>
          </li>
        </ul>
      </div>
    </nav>
    <hr>
    {% block bodyblock %}
    {% endblock %}
    <nav class="navbar fixed-bottom navbar-dark" style="background-color:black;">
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link" href="https://www.facebook.com/dlutton"><i class="fab fa-facebook-f"></i></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://twitter.com/"><i class="fab fa-twitter"></i></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://www.instagram.com/david_lutton/"><i class="fab fa-instagram"></i></a>
        </li>
      </ul>
      <ul class="nav justify-content-center">
          <li class="nav-item"><p class="text-muted"><em>Created by ByteTech</em></p></li>
      </ul>
    </nav>

  </body>
</html>

photography_landing/webpage/templates/webpage/contact.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
  {% block bodyblock %}
    <div class="jumbotron">
      <div id="contact-me">
        <p id="con"class="h1">Contact Me</p>
        <br>
        <br>
        <p class="h4">Email:  dave_lutton@gmail.com</p>
        <p class="h4">Phone:  555-409-9069</p>
      </div>
      <br>
      <br>
      <div class="row">
        <div class="col">
          <img src="{% static 'images/cam-man.jpeg' %}" alt="">
        </div>
        <div class="col">
          <img src="{% static 'images/cam-man2.jpg' %}" alt="">
        </div>
        <div class="col">
          <img src="{% static 'images/cam-man3.jpeg' %}" alt="">
        </div>
      </div>
    </div>

  {% endblock %}

photography_landing/webpage/templates/webpage/home.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
  {% block bodyblock %}
    <div class="jumbotron">
      <h1 class="home-h">Lutton Photograghy</h1>
      <h6 class="home-h">The Nation's Premier City Photographer</h6>
      <br>
      <br>
      <div class="row">
        <div class="col" id="home-col">
          <div id="carouselExampleInterval-1" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active" data-interval="5000">
                  <img id="car-img"src="{% static 'images/LA-2.jpeg' %}" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item" data-interval="5000">
                  <img id="car-img" src="{% static 'images/LA-1.jpeg' %}" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item" data-interval="5000">
                  <img id="car-img" src="{% static 'images/LA-10.jpeg' %}" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item" data-interval="5000">
                  <img id="car-img"src="{% static 'images/sea-12.jpg' %}" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item" data-interval="5000">
                  <img id="car-img" src="{% static 'images/sea-1.jpg' %}" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item" data-interval="5000">
                  <img id="car-img" src="{% static 'images/sea-3.jpeg' %}" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item" data-interval="5000">
                  <img id="car-img" src="{% static 'images/port-3.jpg' %}" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item" data-interval="5000">
                  <img id="car-img" src="{% static 'images/port-5.jpg' %}" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item" data-interval="5000">
                  <img id="car-img" src="{% static 'images/port-6.jpg' %}" class="d-block w-100" alt="...">
                </div>
              </div>
              <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
          </div>
        </div>
      </div>
  </div>

  {% endblock %}

photography_landing/webpage/templates/webpage/losangeles.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block bodyblock %}
  <div class="jumbotron" id="city">
    <h1><strong>Los Angeles</strong></h1>
    <div class="row">
      <div class="column" id='column1'>
        <img id='square' src="{% static 'images/LA-1.jpeg' %}">
        <img id='square' src="{% static 'images/LA-2.jpeg' %}">
        <img id='long' src="{% static 'images/LA-6.jpeg' %}">
      </div>
      <div class="column" id="column2">
        <img id='square' src="{% static 'images/LA-5.jpg' %}">
        <img id='long' src="{% static 'images/LA-4.jpeg' %}">
        <img id='square' src="{% static 'images/LA-3.jpeg' %}">
      </div>
      <div class="column" id="column3">
        <img id='square' src="{% static 'images/LA-9.jpeg' %}">
        <img id='long' src="{% static 'images/LA-7.jpeg' %}">
        <img id='square' src="{% static 'images/LA-8.jpeg' %}">
      </div>
      <div class="column" id="column4">
        <img id='square' src="{% static 'images/LA-10.jpeg' %}">
        <img id='square' src="{% static 'images/LA-13.jpeg' %}">
        <img id='long' src="{% static 'images/LA-12.jpeg' %}">
      </div>

    </div>

  </div>

{% endblock %}

photography_landing/webpage/templates/webpage/portland.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block bodyblock %}
  <div class="jumbotron" id="city">
    <h1><strong>Portland</strong></h1>
    <div class="row">
      <div class="column" id='column1'>
        <img id='square' src="{% static 'images/port-1.jpeg' %}">
        <img id='square' src="{% static 'images/port-9.jpg' %}">
        <img id='long' src="{% static 'images/port-3.jpg' %}">
      </div>
      <div class="column" id="column2">
        <img id='square' src="{% static 'images/port-4.jpg' %}">
        <img id='long' src="{% static 'images/port-5.jpg' %}">
        <img id='square' src="{% static 'images/port-6.jpg' %}">
      </div>
      <div class="column" id="column3">
        <img id='square' src="{% static 'images/port-2.jpeg' %}">
        <img id='long' src="{% static 'images/port-8.jpg' %}">
        <img id='square' src="{% static 'images/port-12.jpg' %}">
      </div>
      <div class="column" id="column4">
        <img id='square' src="{% static 'images/port-10.jpg' %}">
        <img id='square' src="{% static 'images/port-11.jpg' %}">
        <img id='long' src="{% static 'images/port-7.jpg' %}">
      </div>

    </div>

  </div>

{% endblock %}

photography_landing/webpage/templates/webpage/seattle.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block bodyblock %}
  <div class="jumbotron" id="city">
    <h1><strong>Seattle</strong></h1>
    <div class="row">
      <div class="column" id='column1'>
        <img id='square' src="{% static 'images/sea-1.jpg' %}">
        <img id='square' src="{% static 'images/sea-12.jpg' %}">
        <img id='long' src="{% static 'images/sea-3.jpeg' %}">
      </div>
      <div class="column" id="column2">
        <img id='square' src="{% static 'images/sea-4.jpg' %}">
        <img id='long' src="{% static 'images/sea-5.jpg' %}">
        <img id='square' src="{% static 'images/sea-6.jpg' %}">
      </div>
      <div class="column" id="column3">
        <img id='square' src="{% static 'images/sea-2.jpeg' %}">
        <img id='long' src="{% static 'images/sea-7.jpg' %}">
      </div>
      <div class="column" id="column4">
        <img id='square' src="{% static 'images/sea-10.jpg' %}">
        <img id='square' src="{% static 'images/sea-11.jpg' %}">
        <img id='long' src="{% static 'images/sea-8.jpg' %}">
      </div>

    </div>

  </div>

{% endblock %}